### ISSUE TITLE
Credentials set in drop-down list fail on ssh connection (possibly not passed correctly to Ansible?)

### ISSUE THREAD

**Issue by yohay-h** [jenkinsci/ansible-plugin#104]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.414
OS: Linux - 4.18.0-477.13.1.el8_8.x86_64
Java: 11.0.19 - Red Hat, Inc. (OpenJDK 64-Bit Server VM)
---
ansible:240.vc26740a_625c0
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Rocky Linux 8.8

### Reproduction steps

1. In a freestyle job, add an `Invoke Ansible Ad-Hoc Command` step
2. Specify host pattern (e.g: `target_host`)
3. Add a simple Inventory (fails for both inline content, and file) with no creds info, e.g: 
```
[target_host]
10.6.6.6
```
4. Specify `ping` under `Module` (any command would fail, this is just for simplified testing).
5. Select a valid credential from the `Credentials` drop-down list (that you've previously set in Jenkins).
6. Save the Jenkins job and run it.

### Expected Results

 ```
 $ sshpass ******** ansible target_host -i temp_inventory.ini -m ping -f 5 -u ansiblesvc -k
10.6.6.6 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "ping": "pong"
}
```

### Actual Results

```
$ sshpass ******** ansible target_host -i temp_inventory.ini -m ping -f 5 -u ansiblesvc -k
10.6.6.6 | UNREACHABLE! => {
    "changed": false,
    "msg": "Invalid/incorrect password: Permission denied, please try again.",
    "unreachable": true
}
```

### Anything else?

This worked fine in our existing jobs when they were using version `ansible:217.v1696cee03265`
The issues started as we upgraded the plugin to version `ansible:240.vc26740a_625c0`.

After rolling back to version `ansible:217.v1696cee03265` - ssh creds seem to be working fine,
so something must have broken between `ansible:217.v1696cee03265` and `ansible:240.vc26740a_625c0`.

* It's worth noting that the same issues occur when using `Invoke Ansible-Playbook`(which is how we've discovered this issue originally). 
Using the  `Invoke Ansible Ad-Hoc Command` is outlined in the "Reproduction steps" section as a quicker, easier way to replicate the issue.

**Comment by kalemasters** [comment]
We started seeing credential failures in our pipelines after upgrading to 240.vc26740a_625c0 as well. Based on some initial troubleshooting it looks like it might be related to https://github.com/jenkinsci/ansible-plugin/pull/85 for escaping shell special characters, released in 231.va_d0cb_802c621.

**Comment by jonesbusy** [comment]
PR will be rollback until this plugin gets better test coverage. Thanks for your patience

**Comment by jonesbusy** [comment]
Can you confirm it's fixed by https://github.com/jenkinsci/ansible-plugin/releases/tag/253.v4fe719ffdd8a_ ?

**Comment by yohay-h** [comment]
Thanks @jonesbusy!

I can confirm I was able to successfully run an `Invoke Ansible Playbook` build step in a Jenkins freestyle job,
after updating the Ansible plugin version to `253.v4fe719ffdd8a_` .

Credentials seemed to be passed properly as expected.
