### ISSUE TITLE
Extra Variables are being treated as Concealed with a change password button

### ISSUE THREAD

**Issue by Medalibi** [jenkinsci/ansible-plugin#126]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  println("Jenkins: ${Jenkins.instance.getVersion()}")
println("OS: ${System.getProperty('os.name')} - ${System.getProperty('os.version')}")
println("Java: ${System.getProperty('java.version')} - ${System.getProperty('java.vm.vendor')} (${System.getProperty('java.vm.name')})")
println "---"

Jenkins.instance.pluginManager.plugins
  .collect()
  .sort { it.getShortName() }
  .each {
    plugin -> println("${plugin.getShortName()}:${plugin.getVersion()}")
  }
return
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Rocky Linux 8.8

### Reproduction steps

1. From the Jenkins Dashboard, enter an Ansible project
2. Under the project, select `Configure`
3. Scroll down to the `Build Steps` and click the `Advanced` button
4. Under the `Extra Variables` block, all `Value` fields are `Concealed` and offer a button that says `Change Password`

### Expected Results

The Value filed should be treated as any other string field to be filled up with text.

### Actual Results

The Key/Value variables were never concealed before and if some should be there should be a way to enable or disable the concealment. It is not possible to check what was typed in the Value field as it is all hidden checking for typos or what was used on the last run is not possible.

### Anything else?

Nothing else.

**Comment by Medalibi** [comment]
This is a screenshot of the issue:
<img width="1454" alt="Screenshot 2023-09-14 at 16 59 01" src="https://github.com/jenkinsci/ansible-plugin/assets/5444362/e815a8e9-632a-41cf-b74a-f77168ed8a7b">

**Comment by jonesbusy** [comment]
Hi,

This is not a bug but part of a security fix: https://www.jenkins.io/security/advisory/2023-05-16/#SECURITY-3017

Closing this issue then.

Regards,

**Comment by Medalibi** [comment]
Hi, Thanks for pointing out the reason why this changed. I agree it can be a security risk if the variables passed are secret and sensitive but not all variables require this. We keep all our secrets decrypted via Ansible Vault. Will this be a valid feature request, allowing some extra variables to be treated differently with a tick box?

Cheers,
Mo
