### ISSUE TITLE
Workspace folder doesn't exist in newly created ansible pipelines

### ISSUE THREAD

**Issue by bbobbettoS** [jenkinsci/ansible-plugin#147]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Debian 12

### Reproduction steps

1. Step 1: Create a new pipeline and assure that not exists in workspace dir the folder name of that pipeline, for example if the new pipeline name is 'test' assure that not exists the corresponding folder '/var/jenkins_home/workspace/test'
2.  Step 2: Define a declarative pipeline with an ansible step like
```
pipeline {
    agent any
    stages {
        stage('test') {
            steps {
                ansiblePlaybook(playbook: '/ansible/test.yml')
            }
        }
    }
}
```
3. Step 3: Run it

### Expected Results

Pipeline running

### Actual Results

An error complain that workdir folder doesn't exists
'java.io.IOException: Process working directory '/var/jenkins_home/workspace/test' doesn't exist!'

### Anything else?

I have fixed the issue in the CLIRunner class adding `this.ws.mkdirs()` before the line `launcher.launch()` in the execute() method,

**Comment by jonesbusy** [comment]
Hi,

Thanks for your report.

But I'm not sure to understand. 

Is there a conflict with the "pipeline name" and workspace content ? Can you add more details on reproduction steps to know exactly what to do to reproduce the issue ?

**Comment by bbobbettoS** [comment]
Hello,
I'll try to explain better, sorry for my English.
Step 1: Create a new pipeline and name it 'pipelineName'
Step 2: Define a declarative pipeline like this
```
pipeline {
    agent any
    stages {
        stage('test') {
            steps {
                ansiblePlaybook(playbook: '<pathToPlaybook>')
            }
        }
    }
}
```
You can use a simple playbook like this
```
- name: Test playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: "Test"
```
Step 3: Run the pipeline
In my case the pipeline exits with this Error
`java.io.IOException: Process working directory '/var/jenkins_home/workspace/pipelineName' doesn't exist!`
As far as I understand, in Linux, '/var/jenkins_home/workspace/' is the default base path for workspaces. Each pipeline that interacts with the workspace needs a folder within that workspace with is own name, in this case '/var/jenkins_home/workspace/pipelineName'. When a new pipeline is created this folder doesn't exists and hence the error

**Comment by bbobbettoS** [comment]
perhaps this is more understandable
![ansible-plugin](https://github.com/jenkinsci/ansible-plugin/assets/114412356/5c0575e9-ef11-4c8d-893a-d0f27ed5cf4e)

**Comment by jonesbusy** [comment]
Thank you for the details! Yea I was able also to reproduce during interective tests of the PR.

I confirm adding the mkdirs resolve the issue when ansiblePlaybook is the first step of the pipeline

**Comment by jonesbusy** [comment]
Resolved on 285.v2f044b_eb_7a_3e
