### ISSUE TITLE
support check_mode

### ISSUE THREAD

**Issue by apfelchips** [jenkinsci/ansible-plugin#158]
### What feature do you want to see added?

Please add support for running the Job in check_mode aka. --check.

see: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_checkmode.html

I'd like to use a Jenkins Boolean Parameter / Environment Variable like ANSIBLE_CHECK_MODE to set it

The problem is afaik I cat just simply do the following, because `--check` can not be assigned and can not be set via environment variables.
```sh
--check="${ANSIBLE_CHECK_MODE}"
# or
-e ansible_check_mode="${ANSIBLE_CHECK_MODE}"
```

### Are you interested in contributing this feature?
I'll try to, but I haven't touched JAVA code in a long time and never done any Jenkins Plugin Development, so I don't know If I can do this.

**Comment by jonesbusy** [comment]
@apfelchips Can you try [303.vccb_73a_956ecd](https://github.com/jenkinsci/ansible-plugin/releases/tag/303.vccb_73a_956ecd) and make sure it works for you ? Thanks
