### ISSUE TITLE
Ansible-plugin reporting jinja2 error

### ISSUE THREAD

**Issue by geordie12311** [jenkinsci/ansible-plugin#180]
### Jenkins and plugins versions report

Commit message: "Update add_user.yml"
 > git rev-list --no-walk ca7cf49be7aced9030838e677f08730f18361b8e # timeout=10
[ntp_config] $ /bin/sh -xe /tmp/jenkins7648226585525754489.sh
+ ansible-playbook -i /var/lib/jenkins/workspace/ntp_config/configure-playbooks/inventories/hosts /var/lib/jenkins/workspace/ntp_config/configure-playbooks/ntp_config.yml
ERROR: Ansible requires Jinja2 3.0 or newer on the controller. Current version: 2.9.6
Build step 'Execute shell' marked build as failure
Finished: FAILURE

### What Operating System are you using (both controller, and any agents involved in the problem)?

Description:    Ubuntu 23.10
Release:        23.10
Codename:       mantic

ansible [core 2.16.2]
python version = 3.11.6
jinja version = 3.1.2

### Reproduction steps

Shell script used to build:

ansible-playbook -i /var/lib/jenkins/workspace/ntp_config/configure-playbooks/inventories/hosts /var/lib/jenkins/workspace/ntp_config/configure-playbooks/ntp_config.yml

### Expected Results

Expected playbook to complete

### Actual Results

Commit message: "Update add_user.yml"
 > git rev-list --no-walk ca7cf49be7aced9030838e677f08730f18361b8e # timeout=10
[ntp_config] $ /bin/sh -xe /tmp/jenkins7648226585525754489.sh
+ ansible-playbook -i /var/lib/jenkins/workspace/ntp_config/configure-playbooks/inventories/hosts /var/lib/jenkins/workspace/ntp_config/configure-playbooks/ntp_config.yml
ERROR: Ansible requires Jinja2 3.0 or newer on the controller. Current version: 2.9.6
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by jonesbusy** [comment]
https://www.jenkins.io/participate/report-issue/

Looks your Ansible installation is broken with your Jinja2.

Please reopen if you are sure it's actually a plugin problem. And provide a clear example and steps
